# Generated by Django 5.0.2 on 2024-02-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('about', models.CharField(max_length=1000)),
                ('symptoms', models.CharField(max_length=1000)),
                ('treatment', models.CharField(max_length=1000)),
            ],
        ),
    ]
